   
name: Main Workflow
on:
  workflow_dispatch:
    inputs:
      Infra:
        description: 'Choose action for infra'
        required: true
        type: choice
        options:
          - deploy
          - destroy

jobs:
  deployInfra:
    if: ${{ github.event.inputs.Infra == 'deploy' }}
    uses: ./.github/workflows/deploy.yml

  destroyInfra:
    if: ${{ github.event.inputs.Infra == 'destroy' }}
    uses: ./.github/workflows/destroy.yml
