   
name: Main Workflow
on:
  workflow_dispatch:
     inputs:
       Infra:
         description: 'Choose action for infra'
         required: true
         type: choice
         options:
          - deploy
          - destroy

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: | 
           echo "Infra action chosen: ${{ github.event.inputs.Infra }}"

  ExecuteInfraDeployment:
        uses: ./.github/workflows/test.yml
