name: Deploy Infra ACR, AKS
on: 
  workflow_call:

jobs:
  #...DeployAZ...
  DeployResourceAz:
    name: Deploy Resource AZ
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: CLI hola mundo
        run: echo "hola mundo!"
