name: TEST_1
on: 
  workflow_call:
env:
  Var_SemVer: "0.1.2"
  
jobs:
  Test_1:
    name: Example Generate Variable
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Variable
        run: |
          echo "Var_SemVer=${{ env.Var_SemVer }}">>$GITHUB_ENV
          echo ${{ env.Var_SemVer }}
